# MARK: uv-lock
[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.10.7"
hooks = [{ id = "uv-lock", priority = 0 }]

# MARK: pre-commit-hooks
[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"

[[repos.hooks]]
id = "check-merge-conflict"
priority = 0

[[repos.hooks]]
id = "check-added-large-files"
args = ["--maxkb=750"]
exclude = "^uv\\.lock$"
priority = 0

[[repos.hooks]]
id = "check-toml"
priority = 0

[[repos.hooks]]
id = "check-yaml"
args = ["--unsafe"]
priority = 0

[[repos.hooks]]
id = "end-of-file-fixer"
priority = 0

[[repos.hooks]]
id = "trailing-whitespace"
priority = 0

# MARK: validate-pyproject
[[repos]]
repo = "https://github.com/abravalheri/validate-pyproject"
rev = "v0.25"

[[repos.hooks]]
id = "validate-pyproject"
files = "(^pyproject\\.toml$|^packages/voice-chess-server/pyproject\\.toml$|^packages/voice-chess-testkit/pyproject\\.toml$|^examples/server/pyproject\\.toml$)"
priority = 0

# MARK: ruff-format
[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.4"

[[repos.hooks]]
id = "ruff-format"
files = "(^packages/voice-chess-server/|^examples/server/)"
priority = 0

[[repos.hooks]]
id = "ruff"
args = ["--fix", "--exit-non-zero-on-fix"]
files = "(^packages/voice-chess-server/|^examples/server/)"
types_or = ["python", "pyi"]
require_serial = true
priority = 1
